PROJETO 1

organizações internacionais:
UNICEF (5)
UNICEF (12)
UNESCO (10)
OMS (11)(malaria)

In [ ]:
UNESCO e OMS são organizações da ONU e os países nao reconhecidos pela ONU e consequentemente não membros das organizações são:
Taiwan
Saara Ocidental
Ilhas Turcas e Caicos
Kosovo
Curação
Tahiti
Puerto Rico
Mayonette
Aruba
Guiana Francesa
Hong Kong
Macau
Nova Macedonia
Ilhas Faroe
Ilhas Cook
Groelândia
Ilhas Cayman
Martinica
Samoa American
Montserrat
Ilhas Virgens Americanas
Ilhas Virgens Britânicas
Niue
Sint Maarten
Ilhas Reunião
Guadalupe
Bonaire
Anguilla
Tokelau
Guam
Gibraltar

paises que estao versus paises que nao estao  #FAZER

In [ ]:
%matplotlib inline
import pandas as pd
import numpy as np
import math as math
from scipy import stats
import matplotlib.pyplot as plt

In [78]:
#TESTANDO DADOS
print('Esperamos trabalhar no diretório')
print(os.getcwd())

Esperamos trabalhar no diretório
C:\Users\julia\OneDrive\DADOS\aula 2

In [16]:
dados = pd.read_excel('indicator_t above 15 employ.xlsx')
dados.head()

,Total above 15 employment to population (%),1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007
0,Afghanistan,56.700001,56.500000,56.599998,56.200001,56.200001,56.099998,56.200001,56.200001,56.099998,56.099998,56.500000,56.400002,54.400002,56.000000,54.000000,56.000000,55.700001
1,Albania,52.700001,52.299999,52.400002,52.700001,52.799999,52.599998,52.400002,52.099998,52.099998,51.900002,51.799999,51.799999,51.799999,51.700001,51.500000,51.400002,51.400002
2,Algeria,39.400002,38.900002,39.400002,39.400002,38.099998,38.900002,39.700001,39.500000,39.400002,38.599998,40.400002,41.500000,42.799999,46.400002,48.000000,50.000000,50.500000
3,Angola,75.800003,75.800003,75.500000,75.900002,75.800003,75.900002,75.699997,75.599998,75.599998,75.500000,75.500000,75.599998,75.500000,75.500000,75.599998,75.500000,75.699997
4,Argentina,53.599998,53.799999,53.700001,53.799999,53.500000,54.400002,54.900002,55.000000,54.900002,55.500000,55.599998,55.400002,57.299999,57.700001,58.099998,58.400002,58.400002

In [17]:
mortes = pd.read_excel('indicator reported malaria deaths.xlsx')
mortes.head()

,Reported Deaths,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006
0,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,6.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN
1,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25572.0,13376.0,9473.0,14434.0,38598.0,12459.0,13768.0,10220.0
2,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,682.0,544.0,740.0,468.0,707.0,560.0,944.0,322.0,1392.0
3,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.0,23.0,49.0,30.0,27.0,23.0,18.0,19.0,11.0,42.0
4,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2624.0,2808.0,2740.0,4233.0,4032.0,4860.0,4205.0,5224.0,8083.0

In [23]:
mortes_idx = mortes.set_index('Reported Deaths')
mortes_idx.head(10)

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006
Reported Deaths,,,,,,,,,,,,,,,,,
Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,6.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25572.0,13376.0,9473.0,14434.0,38598.0,12459.0,13768.0,10220.0
Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,682.0,544.0,740.0,468.0,707.0,560.0,944.0,322.0,1392.0
Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.0,23.0,49.0,30.0,27.0,23.0,18.0,19.0,11.0,42.0
Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2624.0,2808.0,2740.0,4233.0,4032.0,4860.0,4205.0,5224.0,8083.0
Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,579.0,417.0,483.0,425.0,707.0,1942.0,434.0
Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,836.0,930.0
Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,2.0,2.0,1.0,7.0
Central African Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,374.0,484.0,NaN,535.0,NaN,417.0,859.0,668.0,865.0
Chad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,936.0,944.0,970.0,NaN,NaN,815.0

In [24]:
mortes_idx.describe()

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006
count,21.000000,16.000000,18.000000,19.000000,24.000000,21.000000,28.000000,37.000000,54.000000,49.000000,46.000000,80.000000,84.000000,85.000000,77.000000,75.000000,82.000000
mean,3445.904762,889.625000,576.388889,491.789474,493.541667,367.666667,647.107143,1474.540541,636.148148,1512.632653,1415.739130,847.737500,890.178571,1615.529412,1111.350649,2312.360000,1985.036585
std,12485.897560,1635.275792,977.792600,1085.153629,1209.904307,752.300826,1178.822179,5903.772747,1112.099585,3851.816215,2320.517504,1770.951927,2089.081023,4950.559635,2894.883562,9265.594148,6367.270430
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,2.250000,4.000000,16.250000,21.000000,198.500000,0.000000,0.000000,2.000000,1.000000,5.500000,6.000000
50%,35.000000,25.500000,29.500000,23.000000,17.000000,35.000000,94.000000,104.000000,168.500000,531.000000,654.000000,79.500000,51.500000,52.000000,34.000000,64.000000,62.500000
75%,1020.000000,983.750000,773.000000,579.000000,605.250000,415.000000,642.250000,764.000000,665.750000,1189.000000,1362.500000,623.000000,791.500000,1091.000000,949.000000,1185.500000,853.500000
max,57649.000000,4998.000000,3315.000000,4689.000000,5775.000000,3268.000000,4773.000000,35982.000000,6197.000000,25572.000000,13376.000000,9473.000000,14434.000000,38598.000000,19547.000000,77000.000000,47000.000000

In [38]:
linhas=[ :,"Cape Verde"]
colunas=[1997,1999]
mortes_idx.loc[linhas,colunas]

SyntaxError: invalid syntax (<ipython-input-38-24015076cb6a>, line 1)

In [40]:
mortes_idx[[1998,1999,2000,2001,2002,2003,2004,2005,2006]][:]

,1998,1999,2000,2001,2002,2003,2004,2005,2006
Reported Deaths,,,,,,,,,
Algeria,2.0,6.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN
Angola,NaN,25572.0,13376.0,9473.0,14434.0,38598.0,12459.0,13768.0,10220.0
Benin,682.0,544.0,740.0,468.0,707.0,560.0,944.0,322.0,1392.0
Botswana,23.0,49.0,30.0,27.0,23.0,18.0,19.0,11.0,42.0
Burkina Faso,2624.0,2808.0,2740.0,4233.0,4032.0,4860.0,4205.0,5224.0,8083.0
Burundi,NaN,NaN,579.0,417.0,483.0,425.0,707.0,1942.0,434.0
Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,836.0,930.0
Cape Verde,NaN,NaN,NaN,0.0,1.0,2.0,2.0,1.0,7.0
Central African Republic,374.0,484.0,NaN,535.0,NaN,417.0,859.0,668.0,865.0
Chad,NaN,NaN,NaN,936.0,944.0,970.0,NaN,NaN,815.0
Comoros,NaN,50.0,82.0,16.0,NaN,NaN,28.0,92.0,56.0
"Congo, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253.0
Cote d'Ivoire,1337.0,974.0,730.0,NaN,NaN,NaN,NaN,NaN,NaN
"Congo, Dem. Rep.",NaN,NaN,2540.0,NaN,1928.0,16498.0,NaN,NaN,24347.0
Eritrea,404.0,169.0,94.0,129.0,85.0,70.0,16.0,32.0,17.0
Ethiopia,NaN,NaN,1105.0,1681.0,1607.0,2138.0,3327.0,1086.0,1357.0
Gabon,NaN,NaN,NaN,91.0,NaN,NaN,NaN,474.0,79.0
Ghana,2798.0,2826.0,3230.0,1717.0,1917.0,1680.0,1260.0,1759.0,2832.0
Guinea,13.0,13.0,441.0,517.0,440.0,586.0,528.0,490.0,NaN
Guinea-Bissau,NaN,NaN,1065.0,635.0,780.0,1137.0,565.0,565.0,507.0
Kenya,665.0,1545.0,683.0,NaN,135.0,NaN,NaN,NaN,NaN
Liberia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,877.0
Madagascar,NaN,640.0,591.0,1300.0,1268.0,1091.0,1194.0,1407.0,590.0
Malawi,NaN,4747.0,7139.0,3355.0,5775.0,4767.0,3457.0,5070.0,7132.0
Mali,NaN,583.0,748.0,562.0,826.0,1309.0,1012.0,1285.0,1914.0
Mauritania,279.0,525.0,491.0,337.0,100.0,NaN,NaN,NaN,67.0
Mozambique,896.0,1189.0,1371.0,3400.0,4214.0,3488.0,4150.0,4209.0,5042.0
Namibia,404.0,531.0,918.0,1728.0,1504.0,1106.0,1185.0,1325.0,571.0
Niger,1823.0,2165.0,1009.0,4018.0,2433.0,3135.0,1382.0,9958.0,2570.0
Nigeria,6197.0,4123.0,5667.0,4317.0,4092.0,5343.0,6032.0,6494.0,6586.0
...,...,...,...,...,...,...,...,...,...
Yemen,NaN,NaN,NaN,NaN,NaN,29.0,NaN,NaN,73.0
Armenia,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
Azerbaijan,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
Georgia,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
Kyrgyzstan,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
Russian Federation,NaN,3.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN
Tajikistan,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
Turkey,0.0,0.0,NaN,0.0,0.0,0.0,NaN,NaN,NaN
Turkmenistan,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN
Uzbekistan,NaN,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
Bangladesh,528.0,552.0,484.0,470.0,598.0,1250.0,411.0,NaN,NaN
Bhutan,17.0,NaN,NaN,14.0,11.0,15.0,5.0,5.0,6.0
"Korea, Dem. Rep.",NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN
Democratic Republic of Timor-Leste,NaN,NaN,NaN,NaN,NaN,100.0,65.0,88.0,68.0
India,666.0,NaN,938.0,1015.0,973.0,1006.0,949.0,963.0,1708.0
Indonesia,45.0,NaN,NaN,68.0,197.0,NaN,NaN,NaN,494.0
Myanmar,3182.0,3648.0,2756.0,2814.0,2634.0,2476.0,1982.0,1707.0,1647.0
Nepal,7.0,NaN,0.0,1.0,3.0,5.0,7.0,10.0,42.0
Sri Lanka,115.0,NaN,NaN,53.0,30.0,2.0,2.0,0.0,0.0
Thailand,688.0,740.0,625.0,424.0,361.0,325.0,230.0,71.0,113.0
Cambodia,621.0,891.0,608.0,476.0,457.0,492.0,382.0,296.0,396.0
China,24.0,67.0,39.0,28.0,42.0,52.0,31.0,48.0,38.0
Laos,427.0,338.0,350.0,244.0,195.0,187.0,105.0,77.0,21.0
Malaysia,27.0,21.0,35.0,46.0,39.0,21.0,35.0,33.0,21.0
Papua New Guinea,651.0,567.0,617.0,619.0,678.0,559.0,644.0,731.0,668.0
Philippines,561.0,755.0,536.0,439.0,98.0,162.0,167.0,145.0,109.0
"Korea, Rep.",0.0,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN
Solomon Islands,33.0,23.0,38.0,55.0,59.0,71.0,34.0,38.0,12.0
Vanuatu,0.0,0.0,NaN,2.0,8.0,8.0,1.0,10.0,6.0
Viet Nam,183.0,190.0,148.0,91.0,50.0,50.0,24.0,18.0,41.0

In [42]:
mortes_idx[[2001,2002,2003,2004,2005,2006]][:]

,2001,2002,2003,2004,2005,2006
Reported Deaths,,,,,,
Algeria,1.0,0.0,NaN,NaN,NaN,NaN
Angola,9473.0,14434.0,38598.0,12459.0,13768.0,10220.0
Benin,468.0,707.0,560.0,944.0,322.0,1392.0
Botswana,27.0,23.0,18.0,19.0,11.0,42.0
Burkina Faso,4233.0,4032.0,4860.0,4205.0,5224.0,8083.0
Burundi,417.0,483.0,425.0,707.0,1942.0,434.0
Cameroon,NaN,NaN,NaN,NaN,836.0,930.0
Cape Verde,0.0,1.0,2.0,2.0,1.0,7.0
Central African Republic,535.0,NaN,417.0,859.0,668.0,865.0
Chad,936.0,944.0,970.0,NaN,NaN,815.0
Comoros,16.0,NaN,NaN,28.0,92.0,56.0
"Congo, Rep.",NaN,NaN,NaN,NaN,NaN,253.0
Cote d'Ivoire,NaN,NaN,NaN,NaN,NaN,NaN
"Congo, Dem. Rep.",NaN,1928.0,16498.0,NaN,NaN,24347.0
Eritrea,129.0,85.0,70.0,16.0,32.0,17.0
Ethiopia,1681.0,1607.0,2138.0,3327.0,1086.0,1357.0
Gabon,91.0,NaN,NaN,NaN,474.0,79.0
Ghana,1717.0,1917.0,1680.0,1260.0,1759.0,2832.0
Guinea,517.0,440.0,586.0,528.0,490.0,NaN
Guinea-Bissau,635.0,780.0,1137.0,565.0,565.0,507.0
Kenya,NaN,135.0,NaN,NaN,NaN,NaN
Liberia,NaN,NaN,NaN,NaN,41.0,877.0
Madagascar,1300.0,1268.0,1091.0,1194.0,1407.0,590.0
Malawi,3355.0,5775.0,4767.0,3457.0,5070.0,7132.0
Mali,562.0,826.0,1309.0,1012.0,1285.0,1914.0
Mauritania,337.0,100.0,NaN,NaN,NaN,67.0
Mozambique,3400.0,4214.0,3488.0,4150.0,4209.0,5042.0
Namibia,1728.0,1504.0,1106.0,1185.0,1325.0,571.0
Niger,4018.0,2433.0,3135.0,1382.0,9958.0,2570.0
Nigeria,4317.0,4092.0,5343.0,6032.0,6494.0,6586.0
...,...,...,...,...,...,...
Yemen,NaN,NaN,29.0,NaN,NaN,73.0
Armenia,0.0,0.0,0.0,0.0,0.0,0.0
Azerbaijan,0.0,0.0,0.0,0.0,0.0,0.0
Georgia,0.0,0.0,0.0,0.0,0.0,0.0
Kyrgyzstan,0.0,0.0,0.0,0.0,0.0,0.0
Russian Federation,NaN,2.0,NaN,NaN,NaN,NaN
Tajikistan,0.0,0.0,0.0,NaN,NaN,NaN
Turkey,0.0,0.0,0.0,NaN,NaN,NaN
Turkmenistan,0.0,0.0,0.0,0.0,NaN,NaN
Uzbekistan,0.0,0.0,0.0,0.0,0.0,0.0
Bangladesh,470.0,598.0,1250.0,411.0,NaN,NaN
Bhutan,14.0,11.0,15.0,5.0,5.0,6.0
"Korea, Dem. Rep.",0.0,0.0,0.0,NaN,NaN,NaN
Democratic Republic of Timor-Leste,NaN,NaN,100.0,65.0,88.0,68.0
India,1015.0,973.0,1006.0,949.0,963.0,1708.0
Indonesia,68.0,197.0,NaN,NaN,NaN,494.0
Myanmar,2814.0,2634.0,2476.0,1982.0,1707.0,1647.0
Nepal,1.0,3.0,5.0,7.0,10.0,42.0
Sri Lanka,53.0,30.0,2.0,2.0,0.0,0.0
Thailand,424.0,361.0,325.0,230.0,71.0,113.0
Cambodia,476.0,457.0,492.0,382.0,296.0,396.0
China,28.0,42.0,52.0,31.0,48.0,38.0
Laos,244.0,195.0,187.0,105.0,77.0,21.0
Malaysia,46.0,39.0,21.0,35.0,33.0,21.0
Papua New Guinea,619.0,678.0,559.0,644.0,731.0,668.0
Philippines,439.0,98.0,162.0,167.0,145.0,109.0
"Korea, Rep.",NaN,0.0,0.0,NaN,NaN,NaN
Solomon Islands,55.0,59.0,71.0,34.0,38.0,12.0
Vanuatu,2.0,8.0,8.0,1.0,10.0,6.0
Viet Nam,91.0,50.0,50.0,24.0,18.0,41.0

In [21]:
gasto= pd.read_excel('indicator_per capita government expenditure on health at average exchange rate (us$).xlsx')
gasto.head(10)

,Per capita government expenditure on health at average exchange rate (US$),1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,Abkhazia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.832643,1.250118,1.614160,2.525066,2.813779,3.503426,3.744613,3.908887,4.390408
2,Akrotiri and Dhekelia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,13.940591,17.062074,14.164771,18.625848,28.139706,27.160512,30.509619,32.549902,40.609457,63.935601,71.356600,75.552514,88.762634,109.074284,106.893745,94.023613
4,Algeria,46.771460,47.960053,49.738400,48.670547,45.543825,45.911114,52.509423,54.078381,62.637209,63.229395,69.295636,81.679706,108.904747,147.820706,143.160577,138.840923
5,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Andorra,897.181541,982.794819,966.484960,1338.295221,942.421563,862.391612,889.589911,1022.332657,1297.395724,1517.211905,1628.698412,1853.281652,2102.019346,2369.684492,2357.761806,2172.379162
7,Angola,13.516833,8.724155,10.527305,6.648744,6.548254,12.514473,18.320510,14.311165,19.364537,19.664783,27.121077,50.848735,68.385205,125.545110,180.914189,101.591527
8,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Antigua and Barbuda,233.093441,227.111427,245.814244,263.587486,277.832613,281.392962,265.678108,266.949412,278.509762,290.616312,304.669749,350.984695,396.555105,408.585690,403.158318,489.455700

In [52]:
gasto_idx = gasto.set_index('Per capita government expenditure on health at average exchange rate (US$)')
gasto_idx.head(7)

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
Per capita government expenditure on health at average exchange rate (US$),,,,,,,,,,,,,,,,
Abkhazia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.832643,1.250118,1.614160,2.525066,2.813779,3.503426,3.744613,3.908887,4.390408
Akrotiri and Dhekelia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,13.940591,17.062074,14.164771,18.625848,28.139706,27.160512,30.509619,32.549902,40.609457,63.935601,71.356600,75.552514,88.762634,109.074284,106.893745,94.023613
Algeria,46.771460,47.960053,49.738400,48.670547,45.543825,45.911114,52.509423,54.078381,62.637209,63.229395,69.295636,81.679706,108.904747,147.820706,143.160577,138.840923
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,897.181541,982.794819,966.484960,1338.295221,942.421563,862.391612,889.589911,1022.332657,1297.395724,1517.211905,1628.698412,1853.281652,2102.019346,2369.684492,2357.761806,2172.379162

In [41]:
gasto_idx[[1998,1999,2000,2001,2002,2003,2004,2005,2006]][:]

,1998,1999,2000,2001,2002,2003,2004,2005,2006
Per capita government expenditure on health at average exchange rate (US$),,,,,,,,,
Abkhazia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,NaN,NaN,NaN,0.832643,1.250118,1.614160,2.525066,2.813779
Akrotiri and Dhekelia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Albania,18.625848,28.139706,27.160512,30.509619,32.549902,40.609457,63.935601,71.356600,75.552514
Algeria,48.670547,45.543825,45.911114,52.509423,54.078381,62.637209,63.229395,69.295636,81.679706
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,1338.295221,942.421563,862.391612,889.589911,1022.332657,1297.395724,1517.211905,1628.698412,1853.281652
Angola,6.648744,6.548254,12.514473,18.320510,14.311165,19.364537,19.664783,27.121077,50.848735
Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,263.587486,277.832613,281.392962,265.678108,266.949412,278.509762,290.616312,304.669749,350.984695
Argentina,382.569181,399.605605,381.877315,367.271410,120.725383,148.074723,173.801947,217.021027,258.846316
Armenia,10.010791,9.628055,7.068904,10.996692,10.568109,13.909766,16.276034,23.630190,32.993022
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Australia,1053.227780,1193.335611,1144.752844,1081.669023,1235.744552,1535.714845,1915.153068,2097.856608,2217.438755
Austria,2018.319654,2049.536567,1823.838758,1815.096639,1953.658872,2412.845413,2787.684689,2917.158741,3040.373513
Azerbaijan,5.039245,5.615609,5.635569,5.898770,5.962687,7.206062,10.529927,13.586271,20.838388
Bahamas,457.722606,496.615531,522.675886,523.857047,555.918901,582.217394,633.149687,634.895634,804.412695
Bahrain,329.871736,343.417268,335.484287,353.857203,386.138667,428.010958,443.940742,475.118403,484.676716
Bangladesh,21.206274,22.342381,24.219630,27.127015,29.345671,30.439731,33.698262,37.364670,43.021846
Barbados,346.677672,372.197856,395.553828,428.996234,458.908696,456.330970,472.175814,498.062868,542.453544
Belarus,68.770664,56.633699,47.920292,58.503765,66.805390,87.452119,115.400746,154.438524,168.250178
Belgium,1477.858625,1499.690683,1375.774521,1413.946374,1528.223739,2251.360837,2677.651936,2746.236707,2685.291992
Belize,62.275118,60.997673,69.448539,87.985381,87.226406,95.416942,96.495290,105.014621,113.215112
Benin,7.737780,8.296651,6.940493,8.583070,7.643057,10.978391,11.910787,13.430016,14.260144
Bermuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bhutan,25.026171,38.186153,40.934566,39.290585,58.549131,37.343487,34.937042,43.949195,56.170433
Bolivia,33.286655,36.678654,36.907249,35.960671,37.502081,30.686717,32.599961,38.562196,41.252612
Bosnia and Herzegovina,40.719559,61.847961,60.887673,67.072723,78.790452,123.092615,138.919632,144.462851,169.437381
Botswana,71.287947,75.479017,94.379720,126.256733,145.242939,180.414702,346.122055,310.942780,290.832395
Brazil,143.057917,103.402000,106.753682,96.301297,90.662876,94.771840,121.043907,155.551585,204.988096
...,...,...,...,...,...,...,...,...,...
Tuvalu,119.799768,135.588729,231.439557,245.199310,237.848726,410.033413,370.321590,402.206695,447.005438
Uganda,4.260973,4.904683,4.192087,4.643002,5.200363,5.278057,5.922974,7.256854,7.016396
Ukraine,29.738224,18.821807,18.513720,24.101545,31.014360,42.538423,53.108463,69.975160,89.838614
United Arab Emirates,564.756980,558.892162,576.748804,637.767157,578.235615,611.067469,588.317259,607.500304,658.488588
United Kingdom,1331.428825,1422.588336,1392.935201,1438.300080,1639.444191,1941.456504,2392.048021,2554.011382,2778.884258
United States,1843.058284,1916.391915,2031.765381,2231.182833,2404.820625,2608.070980,2785.602950,2953.582404,3174.434494
Uruguay,288.080870,460.809939,422.054411,379.760747,238.882058,178.351264,172.326203,219.126038,261.954320
USSR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Uzbekistan,18.234128,19.574727,13.972490,11.854792,9.262620,9.459097,10.579564,12.555876,15.939929
Wallis et Futuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vanuatu,44.788020,39.038485,40.226429,37.945984,39.245831,43.440637,45.755352,44.373771,50.804906
Venezuela,57.118210,85.775764,113.562566,120.024889,81.656737,72.464136,99.022717,128.211995,161.575079
West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
West Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Western Sahara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vietnam,6.116791,6.323162,6.466222,7.213242,6.824609,8.145947,8.373131,9.838058,15.353339
Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
North Yemen (former),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Yemen (former),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Yemen,10.129011,10.849342,13.603511,14.322089,14.202218,16.651327,14.460323,14.303650,16.305628
Yugoslavia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,13.570401,9.018808,9.226037,11.728877,14.711695,16.215075,18.407207,24.049212,35.028628
Zimbabwe,29.437772,17.635314,31.487256,25.366150,NaN,NaN,NaN,NaN,NaN
Åland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Christian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Coastline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Curaçao,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sint Maarten (Dutch part),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
St. Martin (French part),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
gasto_idx[[2001,2002,2003,2004,2005,2006]][:]

,2001,2002,2003,2004,2005,2006
Per capita government expenditure on health at average exchange rate (US$),,,,,,
Abkhazia,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,0.832643,1.250118,1.614160,2.525066,2.813779
Akrotiri and Dhekelia,NaN,NaN,NaN,NaN,NaN,NaN
Albania,30.509619,32.549902,40.609457,63.935601,71.356600,75.552514
Algeria,52.509423,54.078381,62.637209,63.229395,69.295636,81.679706
American Samoa,NaN,NaN,NaN,NaN,NaN,NaN
Andorra,889.589911,1022.332657,1297.395724,1517.211905,1628.698412,1853.281652
Angola,18.320510,14.311165,19.364537,19.664783,27.121077,50.848735
Anguilla,NaN,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,265.678108,266.949412,278.509762,290.616312,304.669749,350.984695
Argentina,367.271410,120.725383,148.074723,173.801947,217.021027,258.846316
Armenia,10.996692,10.568109,13.909766,16.276034,23.630190,32.993022
Aruba,NaN,NaN,NaN,NaN,NaN,NaN
Australia,1081.669023,1235.744552,1535.714845,1915.153068,2097.856608,2217.438755
Austria,1815.096639,1953.658872,2412.845413,2787.684689,2917.158741,3040.373513
Azerbaijan,5.898770,5.962687,7.206062,10.529927,13.586271,20.838388
Bahamas,523.857047,555.918901,582.217394,633.149687,634.895634,804.412695
Bahrain,353.857203,386.138667,428.010958,443.940742,475.118403,484.676716
Bangladesh,27.127015,29.345671,30.439731,33.698262,37.364670,43.021846
Barbados,428.996234,458.908696,456.330970,472.175814,498.062868,542.453544
Belarus,58.503765,66.805390,87.452119,115.400746,154.438524,168.250178
Belgium,1413.946374,1528.223739,2251.360837,2677.651936,2746.236707,2685.291992
Belize,87.985381,87.226406,95.416942,96.495290,105.014621,113.215112
Benin,8.583070,7.643057,10.978391,11.910787,13.430016,14.260144
Bermuda,NaN,NaN,NaN,NaN,NaN,NaN
Bhutan,39.290585,58.549131,37.343487,34.937042,43.949195,56.170433
Bolivia,35.960671,37.502081,30.686717,32.599961,38.562196,41.252612
Bosnia and Herzegovina,67.072723,78.790452,123.092615,138.919632,144.462851,169.437381
Botswana,126.256733,145.242939,180.414702,346.122055,310.942780,290.832395
Brazil,96.301297,90.662876,94.771840,121.043907,155.551585,204.988096
...,...,...,...,...,...,...
Tuvalu,245.199310,237.848726,410.033413,370.321590,402.206695,447.005438
Uganda,4.643002,5.200363,5.278057,5.922974,7.256854,7.016396
Ukraine,24.101545,31.014360,42.538423,53.108463,69.975160,89.838614
United Arab Emirates,637.767157,578.235615,611.067469,588.317259,607.500304,658.488588
United Kingdom,1438.300080,1639.444191,1941.456504,2392.048021,2554.011382,2778.884258
United States,2231.182833,2404.820625,2608.070980,2785.602950,2953.582404,3174.434494
Uruguay,379.760747,238.882058,178.351264,172.326203,219.126038,261.954320
USSR,NaN,NaN,NaN,NaN,NaN,NaN
Uzbekistan,11.854792,9.262620,9.459097,10.579564,12.555876,15.939929
Wallis et Futuna,NaN,NaN,NaN,NaN,NaN,NaN
Vanuatu,37.945984,39.245831,43.440637,45.755352,44.373771,50.804906
Venezuela,120.024889,81.656737,72.464136,99.022717,128.211995,161.575079
West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN
West Germany,NaN,NaN,NaN,NaN,NaN,NaN
Western Sahara,NaN,NaN,NaN,NaN,NaN,NaN
Vietnam,7.213242,6.824609,8.145947,8.373131,9.838058,15.353339
Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN
North Yemen (former),NaN,NaN,NaN,NaN,NaN,NaN
South Yemen (former),NaN,NaN,NaN,NaN,NaN,NaN
Yemen,14.322089,14.202218,16.651327,14.460323,14.303650,16.305628
Yugoslavia,NaN,NaN,NaN,NaN,NaN,NaN
Zambia,11.728877,14.711695,16.215075,18.407207,24.049212,35.028628
Zimbabwe,25.366150,NaN,NaN,NaN,NaN,NaN
Åland,NaN,NaN,NaN,NaN,NaN,NaN
South Sudan,NaN,NaN,NaN,NaN,NaN,NaN
Christian,NaN,NaN,NaN,NaN,NaN,NaN
Coastline,NaN,NaN,NaN,NaN,NaN,NaN
Curaçao,NaN,NaN,NaN,NaN,NaN,NaN
Sint Maarten (Dutch part),NaN,NaN,NaN,NaN,NaN,NaN
St. Martin (French part),NaN,NaN,NaN,NaN,NaN,NaN

As informaçoes acima correspondem a uma organização da onu, e por esse motivo, poucous países não fazem parte do grupo, 
por esse motivo, começarei a trabalhar com a OCED ou IARC

In [ ]:
IARC:
    A Agência Internacional de Pesquisa em Câncer (Iarc, na sigla em inglês) é a agência especializada em câncer da Organização Mundial ds Saúde (OMS), estabelecida pela resolução WHA18.44 na 18ª Assembleia Mundial da Saúde, em 20 de maio de 1965.

A Iarc tem como objetivo promover a colaboração internacional na pesquisa em câncer sempre com foco na prevenção da doença. Sua função principal consiste em realizar e coordenar a pesquisa e investigação científica em nível internacional, além de auxiliar na implementação de politicas eficazes para prevenção do câncer.  A pesquisa oferece evidência científica forte e independente para a criação de diretrizes e políticas de controle da doença pelas autoridades internacionais e nacionais.

Além da sua excelência na pesquisa científica, a Agência também é responsável por produzir publicações de alta relevância global sobre câncer. Dentre elas, destacam-se Cancer Incidence in Five Continents e Globocan, de alta relevância sobre estatística mundial de câncer;  Iarc Monographs on the Evaluation of Carcinogenic Risks to Humans (avaliação de risco de agentes cancerígenos para humanos);  Iarc Handbooks of Cancer Prevention (avaliação de estratégias de prevenção do câncer); e WHO Classification of Tumours (classificação anatomopatológica do câncer).

A Iarc tem atualmente 26 Estados Participantes que apoiam e supervisionam o trabalho da Agência, atuando nas suas estruturas de governança: os conselhos Científico e Diretivo. 

    
    
https://www.otempo.com.br/interessa/aumento-do-cancer-no-brasil-e-na-america-latina-preocupa-1.2128557
###O Brasil é membro da Iarc desde 2013, sendo o único país da América Latina. O INCA, representando o Brasil, possui assento tanto no Conselho Diretivo, votado às políticas e decisões da Agência, como no Conselho Científico, marcando posição na estratégia científica da Iarc, e com isso garantindo que sejam consideradas as necessidades de investigação em domínios de especial relevância para o País e para a região sul-americana.

In [ ]:
Nos países de dentro da organização, IARC, possuem menor taxa de mortalidade entre homens por câncer de prostata do que nos países de fora?

In [69]:
a=gasto_idx[[2001,2002]][:]
a

                                                           2001         2002
Per capita government expenditure on health at ...
Abkhazia                                                    NaN          NaN
Afghanistan                                                 NaN     0.832643
Akrotiri and Dhekelia                                       NaN          NaN
Albania                                               30.509619    32.549902
Algeria                                               52.509423    54.078381
American Samoa                                              NaN          NaN
Andorra                                              889.589911  1022.332657
Angola                                                18.320510    14.311165
Anguilla                                                    NaN          NaN
Antigua and Barbuda                                  265.678108   266.949412
Argentina                                            367.271410   120.725383
Armenia                                               10.996692    10.568109
Aruba                                                       NaN          NaN
Australia                                           1081.669023  1235.744552
Austria                                             1815.096639  1953.658872
Azerbaijan                                             5.898770     5.962687
Bahamas                                              523.857047   555.918901
Bahrain                                              353.857203   386.138667
Bangladesh                                            27.127015    29.345671
Barbados                                             428.996234   458.908696
Belarus                                               58.503765    66.805390
Belgium                                             1413.946374  1528.223739
Belize                                                87.985381    87.226406
Benin                                                  8.583070     7.643057
Bermuda                                                     NaN          NaN
Bhutan                                                39.290585    58.549131
Bolivia                                               35.960671    37.502081
Bosnia and Herzegovina                                67.072723    78.790452
Botswana                                             126.256733   145.242939
Brazil                                                96.301297    90.662876
...                                                         ...          ...
Tuvalu                                               245.199310   237.848726
Uganda                                                 4.643002     5.200363
Ukraine                                               24.101545    31.014360
United Arab Emirates                                 637.767157   578.235615
United Kingdom                                      1438.300080  1639.444191
United States                                       2231.182833  2404.820625
Uruguay                                              379.760747   238.882058
USSR                                                        NaN          NaN
Uzbekistan                                            11.854792     9.262620
Wallis et Futuna                                            NaN          NaN
Vanuatu                                               37.945984    39.245831
Venezuela                                            120.024889    81.656737
West Bank and Gaza                                          NaN          NaN
West Germany                                                NaN          NaN
Western Sahara                                              NaN          NaN
Vietnam                                                7.213242     6.824609
Virgin Islands (U.S.)                                       NaN          NaN
North Yemen (former)                                        NaN          NaN
South Yemen (former)                                        NaN          NaN
Yemen                                                 14.322089    14.202218
Yugoslavia                                                  NaN          NaN
Zambia                                                11.728877    14.711695
Zimbabwe                                              25.366150          NaN
Åland                                                       NaN          NaN
South Sudan                                                 NaN          NaN
Christian                                                   NaN          NaN
Coastline                                                   NaN          NaN
Curaçao                                                     NaN          NaN
Sint Maarten (Dutch part)                                   NaN          NaN
St. Martin (French part)                                    NaN          NaN

[265 rows x 2 columns]

In [77]:
g=a.loc[['Colombia','Argentina','Bolivia','Albania','Uruguay','Venezuela','Brazil','Chile','Ecuador','Australia','United States','Vietnam','United Kingdom','Tajikistan','South Africa','Zambia','Switzerland']]
g.sort_values(by=2001,ascending=False)

                                                           2001         2002
Per capita government expenditure on health at ...
United States                                       2231.182833  2404.820625
Switzerland                                         2110.101008  2390.604461
United Kingdom                                      1438.300080  1639.444191
Australia                                           1081.669023  1235.744552
Uruguay                                              379.760747   238.882058
Argentina                                            367.271410   120.725383
Chile                                                159.300402   156.921274
Colombia                                             125.219855   123.146955
Venezuela                                            120.024889    81.656737
Brazil                                                96.301297    90.662876
South Africa                                          90.488029    81.449606
Bolivia                                               35.960671    37.502081
Albania                                               30.509619    32.549902
Ecuador                                               26.985165    36.246979
Zambia                                                11.728877    14.711695
Vietnam                                                7.213242     6.824609
Tajikistan                                             1.646961     1.761175

In [49]:
prostata= pd.read_excel('indicator prostate male mortality.xlsx')
prostata.head(10)

,Prostate Male Mortality,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002
0,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.80
1,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.86,7.12,5.81,8.21,6.73,7.91,10.07,10.17,7.18,8.39
2,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.80
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.10
4,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.23,14.47,15.49,16.33,16.28,17.33,16.49,16.23,15.91,15.61
5,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.70,5.06,3.97,4.50,4.91,5.42,5.13,5.77,5.26,6.26
6,Australia,13.52,14.45,13.36,14.64,14.95,15.35,15.15,15.41,15.21,...,19.67,19.56,18.49,18.46,16.53,16.64,15.59,16.04,15.70,15.85
7,Austria,NaN,NaN,NaN,NaN,NaN,11.99,12.31,14.09,12.41,...,17.81,16.40,17.52,17.00,16.76,15.75,16.63,16.32,15.53,14.63
8,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.86,6.77,6.38,4.07,4.53,3.57,3.75,3.27,6.84,7.27
9,Bahamas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.60

In [54]:
prostata_idx = prostata.set_index('Prostate Male Mortality')
prostata_idx

,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,...,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002
Prostate Male Mortality,,,,,,,,,,,,,,,,,,,,,
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.800000
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.86,7.12,5.81,8.21,6.73,7.91,10.07,10.17,7.18,8.390000
Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800000
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.100000
Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.23,14.47,15.49,16.33,16.28,17.33,16.49,16.23,15.91,15.610000
Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.70,5.06,3.97,4.50,4.91,5.42,5.13,5.77,5.26,6.260000
Australia,13.52,14.45,13.36,14.64,14.95,15.35,15.15,15.41,15.21,15.14,...,19.67,19.56,18.49,18.46,16.53,16.64,15.59,16.04,15.70,15.850000
Austria,NaN,NaN,NaN,NaN,NaN,11.99,12.31,14.09,12.41,13.36,...,17.81,16.40,17.52,17.00,16.76,15.75,16.63,16.32,15.53,14.630000
Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.86,6.77,6.38,4.07,4.53,3.57,3.75,3.27,6.84,7.270000
Bahamas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.600000
Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.900000
Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.200000
Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.97,55.89,61.78,NaN,NaN,NaN,NaN,58.09,54.14,55.300000
Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.06,8.12,9.18,NaN,8.98,9.25,10.08,9.36,10.36,11.420000
Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.300000
Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.48,14.49,7.34,6.13,29.15,34.64,22.11,20.51,28.87,35.200000
Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.000000
Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.700000
Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.100000
Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.800000
Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.800000
Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.39,10.26,10.73,11.24,11.88,12.20,11.80,11.78,12.09,12.120000
Brunei,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.100000
Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.55,8.49,8.29,8.90,9.72,8.94,8.87,8.61,9.54,9.670000
Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.800000
Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.800000
Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.600000
Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.300000
Canada,11.70,10.99,11.91,12.33,12.73,12.75,13.42,12.67,12.83,13.31,...,16.91,16.68,16.77,15.59,15.17,14.88,14.21,14.25,14.07,13.340000
Cape Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.33,17.44,18.70,21.45,21.35,20.63,21.47,21.91,21.57,20.910000
Spain,NaN,7.43,5.94,5.70,6.30,6.64,6.94,7.87,7.68,7.83,...,13.57,13.76,13.76,13.94,13.67,14.06,13.39,12.68,12.78,12.380000
Sri Lanka,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000
Sudan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000
Suriname,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.62,14.90,5.81,17.49,15.39,13.77,NaN,10.900000
Swaziland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.200000
Sweden,NaN,10.96,11.99,12.31,11.93,12.82,13.78,14.63,15.81,16.40,...,21.65,20.65,21.75,21.78,22.49,22.19,22.03,21.93,21.30,19.940000
Switzerland,NaN,14.66,14.20,13.37,13.85,14.44,15.63,14.76,15.78,15.14,...,22.97,23.34,19.87,19.15,18.56,17.98,18.92,17.85,17.59,16.340000
Syria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.500000
Tajikistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.41,1.63,1.38,1.24,1.08,1.34,1.60,1.94,2.54,1.650000
Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.400000
Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02,0.03,...,NaN,0.28,0.33,0.43,0.25,0.33,0.51,0.83,NaN,1.080000
Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.000000
Trinidad and Tobago,NaN,3.88,2.20,4.41,7.64,7.44,7.81,9.97,4.96,NaN,...,34.22,44.73,51.11,46.82,49.18,41.15,47.44,39.72,42.91,51.420000
Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000
Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.61,1.40,1.65,0.80,1.08,1.32,NaN,NaN,NaN,1.500000
Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.500000
Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.93,7.48,7.15,7.06,7.32,7.44,7.75,7.84,7.63,8.340000
United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.500000
United Kingdom,10.73,10.56,10.30,10.79,11.32,11.25,12.04,11.65,11.90,11.75,...,17.09,17.04,17.23,16.69,16.03,15.84,15.66,15.01,15.74,15.590000
United States,13.24,13.04,13.51,13.55,13.86,13.83,14.02,14.04,13.56,13.26,...,17.20,16.83,16.35,15.76,14.78,14.07,13.50,12.87,12.39,12.030000
Uruguay,NaN,NaN,NaN,NaN,NaN,11.88,15.21,14.42,12.55,14.81,...,19.45,21.25,22.12,23.20,19.92,21.34,20.56,21.04,21.78,22.096667
Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.03,1.14,1.49,1.10,1.49,1.39,1.42,1.92,NaN,2.020000
Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.200000
Venezuela,NaN,NaN,NaN,NaN,NaN,8.48,7.36,8.48,8.91,7.85,...,16.36,19.47,NaN,20.44,19.20,19.39,18.78,19.82,20.18,19.940000
Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.700000
"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.000000
Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.500000

In [55]:
prostata_idx[[1998,1999,2000,2001,2002]][:]

                          1998   1999   2000   2001       2002
Prostate Male Mortality
Afghanistan                NaN    NaN    NaN    NaN   2.800000
Albania                   7.91  10.07  10.17   7.18   8.390000
Algeria                    NaN    NaN    NaN    NaN   4.800000
Angola                     NaN    NaN    NaN    NaN  11.100000
Argentina                17.33  16.49  16.23  15.91  15.610000
Armenia                   5.42   5.13   5.77   5.26   6.260000
Australia                16.64  15.59  16.04  15.70  15.850000
Austria                  15.75  16.63  16.32  15.53  14.630000
Azerbaijan                3.57   3.75   3.27   6.84   7.270000
Bahamas                    NaN    NaN    NaN    NaN  35.600000
Bahrain                    NaN    NaN    NaN    NaN   9.900000
Bangladesh                 NaN    NaN    NaN    NaN   0.200000
Barbados                   NaN    NaN  58.09  54.14  55.300000
Belarus                   9.25  10.08   9.36  10.36  11.420000
Belgium                    NaN    NaN    NaN    NaN  20.300000
Belize                   34.64  22.11  20.51  28.87  35.200000
Benin                      NaN    NaN    NaN    NaN  16.000000
Bhutan                     NaN    NaN    NaN    NaN   2.700000
Bolivia                    NaN    NaN    NaN    NaN  19.100000
Bosnia and Herzegovina     NaN    NaN    NaN    NaN  10.800000
Botswana                   NaN    NaN    NaN    NaN  25.800000
Brazil                   12.20  11.80  11.78  12.09  12.120000
Brunei                     NaN    NaN    NaN    NaN   4.100000
Bulgaria                  8.94   8.87   8.61   9.54   9.670000
Burkina Faso               NaN    NaN    NaN    NaN  11.800000
Burundi                    NaN    NaN    NaN    NaN  11.800000
Cambodia                   NaN    NaN    NaN    NaN   4.600000
Cameroon                   NaN    NaN    NaN    NaN  21.300000
Canada                   14.88  14.21  14.25  14.07  13.340000
Cape Verde                 NaN    NaN    NaN    NaN  16.000000
...                        ...    ...    ...    ...        ...
South Africa             20.63  21.47  21.91  21.57  20.910000
Spain                    14.06  13.39  12.68  12.78  12.380000
Sri Lanka                  NaN    NaN    NaN    NaN   2.000000
Sudan                      NaN    NaN    NaN    NaN   6.000000
Suriname                 17.49  15.39  13.77    NaN  10.900000
Swaziland                  NaN    NaN    NaN    NaN  17.200000
Sweden                   22.19  22.03  21.93  21.30  19.940000
Switzerland              17.98  18.92  17.85  17.59  16.340000
Syria                      NaN    NaN    NaN    NaN  12.500000
Tajikistan                1.34   1.60   1.94   2.54   1.650000
Tanzania                   NaN    NaN    NaN    NaN  17.400000
Thailand                  0.33   0.51   0.83    NaN   1.080000
Togo                       NaN    NaN    NaN    NaN  16.000000
Trinidad and Tobago      41.15  47.44  39.72  42.91  51.420000
Tunisia                    NaN    NaN    NaN    NaN   7.000000
Turkey                     NaN    NaN    NaN    NaN   5.000000
Turkmenistan              1.32    NaN    NaN    NaN   1.500000
Uganda                     NaN    NaN    NaN    NaN  32.500000
Ukraine                   7.44   7.75   7.84   7.63   8.340000
United Arab Emirates       NaN    NaN    NaN    NaN   6.500000
United Kingdom           15.84  15.66  15.01  15.74  15.590000
United States            14.07  13.50  12.87  12.39  12.030000
Uruguay                  21.34  20.56  21.04  21.78  22.096667
Uzbekistan                1.39   1.42   1.92    NaN   2.020000
Vanuatu                    NaN    NaN    NaN    NaN   1.200000
Venezuela                19.39  18.78  19.82  20.18  19.940000
Vietnam                    NaN    NaN    NaN    NaN   1.700000
Yemen, Rep.                NaN    NaN    NaN    NaN   1.000000
Zambia                     NaN    NaN    NaN    NaN  14.000000
Zimbabwe                   NaN    NaN    NaN    NaN  23.500000

[176 rows x 5 columns]

In [74]:
x=prostata_idx[[2001,2002]][:]
x

                          2001       2002
Prostate Male Mortality
Afghanistan                NaN   2.800000
Albania                   7.18   8.390000
Algeria                    NaN   4.800000
Angola                     NaN  11.100000
Argentina                15.91  15.610000
Armenia                   5.26   6.260000
Australia                15.70  15.850000
Austria                  15.53  14.630000
Azerbaijan                6.84   7.270000
Bahamas                    NaN  35.600000
Bahrain                    NaN   9.900000
Bangladesh                 NaN   0.200000
Barbados                 54.14  55.300000
Belarus                  10.36  11.420000
Belgium                    NaN  20.300000
Belize                   28.87  35.200000
Benin                      NaN  16.000000
Bhutan                     NaN   2.700000
Bolivia                    NaN  19.100000
Bosnia and Herzegovina     NaN  10.800000
Botswana                   NaN  25.800000
Brazil                   12.09  12.120000
Brunei                     NaN   4.100000
Bulgaria                  9.54   9.670000
Burkina Faso               NaN  11.800000
Burundi                    NaN  11.800000
Cambodia                   NaN   4.600000
Cameroon                   NaN  21.300000
Canada                   14.07  13.340000
Cape Verde                 NaN  16.000000
...                        ...        ...
South Africa             21.57  20.910000
Spain                    12.78  12.380000
Sri Lanka                  NaN   2.000000
Sudan                      NaN   6.000000
Suriname                   NaN  10.900000
Swaziland                  NaN  17.200000
Sweden                   21.30  19.940000
Switzerland              17.59  16.340000
Syria                      NaN  12.500000
Tajikistan                2.54   1.650000
Tanzania                   NaN  17.400000
Thailand                   NaN   1.080000
Togo                       NaN  16.000000
Trinidad and Tobago      42.91  51.420000
Tunisia                    NaN   7.000000
Turkey                     NaN   5.000000
Turkmenistan               NaN   1.500000
Uganda                     NaN  32.500000
Ukraine                   7.63   8.340000
United Arab Emirates       NaN   6.500000
United Kingdom           15.74  15.590000
United States            12.39  12.030000
Uruguay                  21.78  22.096667
Uzbekistan                 NaN   2.020000
Vanuatu                    NaN   1.200000
Venezuela                20.18  19.940000
Vietnam                    NaN   1.700000
Yemen, Rep.                NaN   1.000000
Zambia                     NaN  14.000000
Zimbabwe                   NaN  23.500000

[176 rows x 2 columns]

In [75]:
y=x.loc[['Colombia','Argentina','Bolivia','Uruguay','Venezuela','Brazil','Chile','Ecuador','Australia','United States','United Kingdom','Tajikistan','South Africa','Switzerland']]
y.sort_values(by=2001,ascending=False)

                          2001       2002
Prostate Male Mortality
Uruguay                  21.78  22.096667
South Africa             21.57  20.910000
Venezuela                20.18  19.940000
Chile                    17.84  17.900000
Switzerland              17.59  16.340000
Argentina                15.91  15.610000
United Kingdom           15.74  15.590000
Australia                15.70  15.850000
Colombia                 15.15  14.970000
United States            12.39  12.030000
Brazil                   12.09  12.120000
Ecuador                  11.22  10.310000
Tajikistan                2.54   1.650000
Bolivia                    NaN  19.100000

In [68]:
data = g.join(y, how="inner")
data.head(7)

ValueError: columns overlap but no suffix specified: Index([1998, 1999, 2000, 2001, 2002], dtype='object')